// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zoo.Infrastructure;

#nullable disable

namespace Zoo.Infrastructure.Migrations
{
    [DbContext(typeof(ZooContext))]
    partial class ZooContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zoo.Infrastructure.Models.AnimalModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ZooKeeperModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZooKeeperModelId");

                    b.ToTable("Animals", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.FoodModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalModelId")
                        .IsUnique();

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.ZooKeeperModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ZooKeepers");
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.BirdModel", b =>
                {
                    b.HasBaseType("Zoo.Infrastructure.Models.AnimalModel");

                    b.Property<string>("BeakType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CanFly")
                        .HasColumnType("boolean");

                    b.Property<double>("WingSpan")
                        .HasColumnType("double precision");

                    b.ToTable("Birds", (string)null);
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.MammalModel", b =>
                {
                    b.HasBaseType("Zoo.Infrastructure.Models.AnimalModel");

                    b.Property<string>("FurColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPredator")
                        .HasColumnType("boolean");

                    b.ToTable("Mammals", (string)null);
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.AnimalModel", b =>
                {
                    b.HasOne("Zoo.Infrastructure.Models.ZooKeeperModel", "ZooKeeper")
                        .WithMany("Animals")
                        .HasForeignKey("ZooKeeperModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZooKeeper");
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.FoodModel", b =>
                {
                    b.HasOne("Zoo.Infrastructure.Models.AnimalModel", "Animal")
                        .WithOne("Food")
                        .HasForeignKey("Zoo.Infrastructure.Models.FoodModel", "AnimalModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.BirdModel", b =>
                {
                    b.HasOne("Zoo.Infrastructure.Models.AnimalModel", null)
                        .WithOne()
                        .HasForeignKey("Zoo.Infrastructure.Models.BirdModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.MammalModel", b =>
                {
                    b.HasOne("Zoo.Infrastructure.Models.AnimalModel", null)
                        .WithOne()
                        .HasForeignKey("Zoo.Infrastructure.Models.MammalModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.AnimalModel", b =>
                {
                    b.Navigation("Food")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Infrastructure.Models.ZooKeeperModel", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
